insert into email_settings (sentfrom, personal, template, sending) values ('test@scottishfriendly.co.uk','test-email-notificatons', 'dailytemplate', 1)
insert into job (description, days,  enabled, last_run, comments,  email_settings_id) values ('IPTR', 1, 1, {ts '2012-09-17 18:47:52.69'}, 'My Plans correspondence awaiting your action', 1)
insert into job (description, days,  enabled, last_run, comments,  email_settings_id) values ('DISABLED', 1, 0, {ts '2012-09-17 18:47:52.69'}, 'Disabled', 1)
insert into code (description,  job_id, threshold, usecontactthreshold, comments) values ('TWEL', 1, 1, 0, 'New Business Welcome Letter')
insert into code (description,  job_id, threshold, usecontactthreshold) values ('TPSR', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('C004', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('C014', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('C016', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('C017', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L102', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L007', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L009', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L010', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L014', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L015', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L017', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L018', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L019', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L021', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L022', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L025', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L044', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L053', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L057', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L060', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L062', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L063', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L067', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L075', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L077', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L084', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L099', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L100', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L102', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L10N', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L10R', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L112', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L113', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L115', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('L130', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('SL02', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('SL03', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('SL04', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('IS07', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('IS11', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('IS12', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('TI3P', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('TIAP', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('TMLS', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('TNIR', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('UT01', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('UT09', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('UT11', 1, 1, 0)
insert into code (description,  job_id, threshold, usecontactthreshold) values ('UT18', 1, 1, 0)

insert into log (comments, end_date, query_counter, send_counter, start_date, job_id) values ('test first log', {ts '2012-09-17 18:49:52.69'}, 42, 23, {ts '2012-09-17 18:47:52.69'}, 1)
insert into log (comments, end_date, query_counter, send_counter, start_date, job_id) values ('test second log', {ts '2012-09-18 18:49:52.69'}, 42, 23, {ts '2012-09-17 18:47:52.69'}, 1)

insert into contact (comments, date_email_address_last_updated, email_address, external_id) values ('My First Contact', {ts '2012-09-17 18:47:52.69'}, 'test1@test.com', 50661031)
insert into contact (comments, date_email_address_last_updated, email_address, external_id) values ('My Second Contact', {ts '2012-09-18 18:47:52.69'}, 'test2@test.com', 50661032)
insert into contact (comments, date_email_address_last_updated, email_address, external_id) values ('My Third Contact', {ts '2012-09-19 18:47:52.69'}, 'test3@test.com', 50661033)
insert into contact (comments, date_email_address_last_updated, email_address, external_id) values ('My Fourth Contact', {ts '2012-09-20 18:47:52.69'}, 'test4@test.com', 50661034)
insert into contact (comments, date_email_address_last_updated, email_address, external_id) values ('My Fifth Contact', {ts '2012-09-21 18:47:52.69'}, 'test5@test.com', 50661035)

insert into letter (comments, accountnumber, counter, letter_id, letter_sent_date, sent, code_id, contact_id, log_id) values ('New Business Welcome Letter'              , 'T325914', 1, 56116426, {ts '2012-09-17 18:47:52.69'}, 1, 1, 1, 1)
insert into letter (comments, accountnumber, counter, letter_id, letter_sent_date, sent, code_id, contact_id, log_id) values ('New Business Welcome Letter'              , 'T325917', 1, 56116427, {ts '2012-09-17 18:47:52.69'}, 1, 1, 2, 2)
insert into letter (comments, accountnumber, counter, letter_id, letter_sent_date, sent, code_id, contact_id, log_id) values ('Post Sales Illustration (Regular Premium)', 'T325914', 1, 56116428, {ts '2012-09-17 18:47:52.69'}, 1, 2, 1, 1)